_target_: pytorch_lightning.Trainer
default_root_dir: ${hydra:run:dir}
min_epochs: 1
max_epochs: 6
# max_epochs: 12
accelerator: gpu

# gradient_clip_val: 0.5
# gradient_clip_algorithm: value
# gradient_clip_val: 5e-2
gradient_clip_val: 2.0
gradient_clip_algorithm: norm
check_val_every_n_epoch: 1
devices: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
