# @package _global_
# overriding hydra default config
hydra:
  job:
    name: train
  run:
    dir: ${dir.output_dir}

defaults:
  - _self_
  - trainer: basic_trainer
  - model: seg_model
  - dataset: seg_dataset
  - dir: concat_label
  - splits: debug
  - callbacks: default
  - logger: wandb
  - extras: default

tag: ["segmentation", "input_allview" ]

competition_name: RSNA2024se # segで分ける
seed: 42
# 間違って実験を上書きしたくないので実験名に日時を追加
exp_name: default
suffix: ${now:%Y%m%d_%H%M%S}
fold: ${splits.fold}
preprocessed_img_size: 128
img_size: 128
in_channels: 1
ckpt_path: null