ARG CONTAIER_VER=153

FROM gcr.io/kaggle-gpu-images/python:v${CONTAIER_VER}

ENV lang="ja_jp.utf-8" language="ja_jp:ja" lc_all="ja_jp.utf-8"

# when you cannot use ssh
ENV LD_LIBRARY_PATH=/usr/local/lib

RUN pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu118
RUN pip install hydra-core segmentation-models-pytorch

WORKDIR /kaggle
ENV PYTHONPATH=$PYTHONPATH:/kaggle/src
