_target_: src.model.model_module.ModelModule

model_architectures:
  _target_: src.model.architectures.model_architectures.ModelArchitectures
  model_config:
    model_name: basic_model
    backbone_name: "tf_efficientnet_b0_ns"
    # backbone_name: "tf_efficientnet_b3_ns"
    pretrained: true
    in_channels: ${in_channels}
    img_encoder_out_channels: 256
    feature_idx: 3 # not used
    # target_num: 25
    target_num: 10 # AxialT2:10, SagittalT1: 10, SagittalT2STIR: 5
    out_channels: 3
    aux_out_channels: 1 # not used
    use_batchnorm: true
    dropout: 0.3

criterion:
  _target_: src.model.losses.LossModule
  loss_config:
    # loss_name: "SevereLoss"
    # loss_name: "BCEWithOnehotLoss"
    loss_name: "WeightedBCEWithOnehotLoss"
    pos_weight: null
    aux_weight: 0.3 # not used

metrics:
  _target_ :  src.metrics.competition_metrics.CompetitionMetrics
  metrics_type: "each"

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  # lr: 0.0005
  lr: 0.001
  weight_decay: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  _partial_: true
  T_0: ${trainer.max_epochs}
  T_mult: 1
  eta_min: 1e-6
  last_epoch: -1
  verbose: false


compile: false

oof_dir: ${dir.output_dir}

target_columns:
# - 'spinal_canal_stenosis_l1_l2'
# - 'spinal_canal_stenosis_l2_l3'
# - 'spinal_canal_stenosis_l3_l4'
# - 'spinal_canal_stenosis_l4_l5'
# - 'spinal_canal_stenosis_l5_s1'
# - 'left_neural_foraminal_narrowing_l1_l2'
# - 'left_neural_foraminal_narrowing_l2_l3'
# - 'left_neural_foraminal_narrowing_l3_l4'
# - 'left_neural_foraminal_narrowing_l4_l5'
# - 'left_neural_foraminal_narrowing_l5_s1'
# - 'right_neural_foraminal_narrowing_l1_l2'
# - 'right_neural_foraminal_narrowing_l2_l3'
# - 'right_neural_foraminal_narrowing_l3_l4'
# - 'right_neural_foraminal_narrowing_l4_l5'
# - 'right_neural_foraminal_narrowing_l5_s1'
- 'left_subarticular_stenosis_l1_l2'
- 'left_subarticular_stenosis_l2_l3'
- 'left_subarticular_stenosis_l3_l4'
- 'left_subarticular_stenosis_l4_l5'
- 'left_subarticular_stenosis_l5_s1'
- 'right_subarticular_stenosis_l1_l2'
- 'right_subarticular_stenosis_l2_l3'
- 'right_subarticular_stenosis_l3_l4'
- 'right_subarticular_stenosis_l4_l5'
- 'right_subarticular_stenosis_l5_s1'
